gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/todo_app_go_frame"
        descriptionTag: true

  docker:
    # 在 mac m1（arm64 架构）下构建 linux/arm64 镜像
    build: "-s linux -a arm64 -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
