# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
# database:
#   default:
#     link: "mysql:root:123456@tcp(127.0.0.1:3306)/todo_app_go_frame"
#     debug: true

database:
  default:
    # 彻底修正：使用 Docker 服务名 'db'
    # 使用我们在 docker-compose.yaml 中定义的用户名、密码和数据库名
    link: "mysql:gouser:gopassword@tcp(db:3306)/todo_db?charset=utf8mb4"
    debug: true
