# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
# 本地开发用
# database:
#   default:
#     link: "mysql:root:123456@tcp(127.0.0.1:3306)/todo_app_go_frame?charset=utf8mb4"
#     debug: true


# docker 容器用
database:
   default:
    link: "mysql:gouser:gopassword@tcp(db:3306)/todo_db?charset=utf8mb4" 
    debug: true
